### ISSUE TITLE
Got Another Problem

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [wootguy/bspguy#102]
When I had decided to redo BSPGuy Master, I for some reason got this error.

LINK : fatal error LNK1181: cannot open input file '..\glew\lib\Release\x64\glew32s.lib' [C:\bspguy-master\build\bspguy
.vcxproj]

**Comment by wootguy** [comment]
Check that the path exists. If it doesn't, check step 5 here:
https://github.com/wootguy/bspguy#windows-users

**Comment by ToxicHolyGrenade** [comment]
As it turns it, it does exist, though in fairness, I _did_ make a mistake about not choosing Windows 32-bit and 64-bit, but I still ran into issues despite learning from that minor mistake.

glfw3.lib(input.obj) : error LNK2019: unresolved external symbol __imp_strspn referenced in function glfwUpdateGamepadM
appings [C:\bspguy-master\build\bspguy.vcxproj]
C:\bspguy-master\build\Release\bspguy.exe : fatal error LNK1120: 1 unresolved externals [C:\bspguy-master\build\bspguy.
vcxproj]

**Comment by wootguy** [comment]
I probably need to link to a specific version of GLFW. That could be a problem with the latest version.

**Comment by Outerbeast** [comment]
> As it turns it, it does exist, though in fairness, I _did_ make a mistake about not choosing Windows 32-bit and 64-bit, but I still ran into issues despite learning from that minor mistake.
> 
> glfw3.lib(input.obj) : error LNK2019: unresolved external symbol __imp_strspn referenced in function glfwUpdateGamepadM appings [C:\bspguy-master\build\bspguy.vcxproj] C:\bspguy-master\build\Release\bspguy.exe : fatal error LNK1120: 1 unresolved externals [C:\bspguy-master\build\bspguy. vcxproj]

I concur this is the exact same problem I ran into using the latest version of GLFW. I believe the release build was built with version 3.3.4 https://github.com/glfw/glfw/releases. When I tried building using that version it introduced its own set of errors
