### ISSUE TITLE
Remove unused visdata, bspguy and maps corrupted 

### ISSUE THREAD

**Issue by UnrealKaraulov** [wootguy/bspguy#104]
https://github.com/wootguy/bspguy/blob/988fc70d0c1ea71b23f624b53296ce6ee2569ed3/src/bsp/Bsp.cpp#L1227

@wootguy, this function cause buffer overrun in every map!!!

After calling, it can cause 50/50 random crash on some maps, or random data corruption, or nothing. I tried to debug this function, and in 90% maps it out of bounds. Some maps (with big overrun) can crashes instantly as in this issue:https://github.com/wootguy/bspguy/issues/78

You can fix it?

**Comment by UnrealKaraulov** [comment]
I think oldVisRowSize has misprint, or passed bad leaf count.

**Comment by UnrealKaraulov** [comment]
I tried to fix it in https://github.com/wootguy/bspguy/pull/105

**Comment by UnrealKaraulov** [comment]
you can add checks in decompressvis for src/dst out of bounds, It found overrun on 90% maps, even on de_dust2 from cs 1.6

**Comment by UnrealKaraulov** [comment]
@wootguy problem in removeunusedvis function, and in decompressvis (iterlevel started from i + 1 index, i think need from i) 

I just don't know how to work this functions, and can't fix it

**Comment by wootguy** [comment]
False alarm, it was a problem in the fork:
https://github.com/wootguy/bspguy/pull/105#issuecomment-1365600213

**Comment by UnrealKaraulov** [comment]
@wootguy problem in maps, some maps has underflowed light data, like https://github.com/wootguy/bspguy/issues/78 

I added and fixed more checks for Decompress/Compress functions, like src size, dst size, leaf size, etc...And it detect buffer overrun on these maps)
