### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by kingbit1999** [wootguy/bspguy#110]
Hello, a question, I try to export the model but it doesn't show me anything. I copy and paste. It turns out I see everything invisible. do you have any ideas?
I can't change textures either

![image](https://github.com/wootguy/bspguy/assets/95147271/14d19041-16cb-4bb5-be87-88553cd578e2)

![image](https://github.com/wootguy/bspguy/assets/95147271/2bec8a01-ebf1-403b-88da-625acee8d187)

**Comment by KarKarKarKarkarkar** [comment]
@kingbit1999 need configure valid fgd/wad path's

**Comment by wootguy** [comment]
This probably works better in [newbspguy](https://github.com/UnrealKaraulov/newbspguy). I removed the import/export stuff in master for now.
