### ISSUE TITLE
Map could not use problem.

### ISSUE THREAD

**Issue by liudonghua123** [wootguy/bspguy#111]
Hi, I got a map from other source (http://cscspt.com/), and I want to play it on my local CS 1.6, But I got the error `Mod LoadBrushModel: maps/cscspt_assault.bsp has wrong version number (142099180 should be 30)`. Can I use this tool to edit the map to make it work for my local CS 1.6. If it can, how can I do it?

<img width="302" alt="9943a129b196b1ebb62aca8bafe4ae1" src="https://github.com/wootguy/bspguy/assets/2276718/0cbc7f0c-5ee4-4263-9f0a-01e4a7fd3615">

[cscspt_assault.zip](https://github.com/wootguy/bspguy/files/13661961/cscspt_assault.zip)

**Comment by KarKarKarKarkarkar** [comment]
@liudonghua123 how to run this game? All in Japanese language, how to change to English?

**Comment by liudonghua123** [comment]
> > Hi, I got a map from other source (http://cscspt.com/), and I want to play it on my local CS 1.6, But I got the error `Mod LoadBrushModel: maps/cscspt_assault.bsp has wrong version number (142099180 should be 30)`. Can I use this tool to edit the map to make it work for my local CS 1.6. If it can, how can I do it?
> > 
> > <img alt="9943a129b196b1ebb62aca8bafe4ae1" width="302" src="https://private-user-images.githubusercontent.com/2276718/290227708-0cbc7f0c-5ee4-4263-9f0a-01e4a7fd3615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODU2MDYsIm5iZiI6MTcwMjQ4NTMwNiwicGF0aCI6Ii8yMjc2NzE4LzI5MDIyNzcwOC0wY2JjN2YwYy01ZWU0LTQyNjMtOWYwYS0wMWU0YTdmZDM2MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMTYzNTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWY1ZTFlNThhNmYwYzRjMTY2YmZlOGZmOWFiZWE3MGQ2NWQyZjgxOGVlYzkwM2JiMTMzZDcyZGY3MGZkZTk2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uTPu3-0WVyeKwRnyY5vGJ9MJIGQkqVsLHI5KZxtFlQE">
> > [cscspt_assault.zip](https://github.com/wootguy/bspguy/files/13661961/cscspt_assault.zip)
> 
> @liudonghua123 File is packed, because no text found data like enities lump.
> 
> Or .BSP format not supported.

@UnrealKaraulov Hi, what does you mean packed, is it encrypted? Need some other file?
What's the difference of this bsp and normal bsp file?

**Comment by Qwertyus3D** [comment]
It doesn't look like valid bsp-file at all. I opened it with HEX editor, and there are no signs that it's a proper map.

**Comment by liudonghua123** [comment]
> @liudonghua123 how to run this game? All in Japanese language, how to change to English?

@KarKarKarKarkarkar It's Chinese language, not Japanese. Maybe it does not support English. 😢

**Comment by liudonghua123** [comment]
> It doesn't look like valid bsp-file at all. I opened it with HEX editor, and there are no signs that it's a proper map. Maybe it's for some kind of asian game, not for normal CS.

@Qwertyus3D Yeah, I opened `cscspt_assault.bsp` and `cs_assault.bsp` in 010 Editor, the header of bits is different. Maybe http://cscspt.com/ changed the map process of CS Client.

**Comment by KarKarKarKarkarkar** [comment]
> > @liudonghua123 how to run this game? All in Japanese language, how to change to English?
> 
> @KarKarKarKarkarkar It's Chinese language, not Japanese. Maybe it does not support English. 😢

Need register?
How to run this game ?

**Comment by KarKarKarKarkarkar** [comment]
@liudonghua123 
I can't find decode/encode function in PSEUDOCODE of cscspt binaries
[CSCSPT_CLIENT_SRC.zip](https://github.com/wootguy/bspguy/files/13671141/CSCSPT_CLIENT_SRC.zip)

**Comment by KarKarKarKarkarkar** [comment]
Part of data without encryption, cscspt_dust.bsp for example

**Comment by liudonghua123** [comment]
> @liudonghua123 I can't find decode/encode function in PSEUDOCODE of cscspt binaries [CSCSPT_CLIENT_SRC.zip](https://github.com/wootguy/bspguy/files/13671141/CSCSPT_CLIENT_SRC.zip)

Hi, what's the tools you used to decompile the executables? I am just curious.

And is it possible that the cscspt client do some decryption or decoding when loading the cscspt_dust.bsp? Maybe we can monitor the files opened when runing to find the actual map used.

**Comment by KarKarKarKarkarkar** [comment]
@liudonghua123 

I got this files from source that use IDA 8.3 PRO HEX RAYS decompiler. 

hw.dll also encrypted. 

Possible, antihack used for decrypt this files, but I can't test without running this game.
