### ISSUE TITLE
Hello wootguy

### ISSUE THREAD

**Issue by fakeholdmygroza** [wootguy/bspguy#118]
I found many issues with bspguy like lightmaps/textures/func wall and many things
could you give me ur discord or anything so i can contact you from there and explain 

This is my Discord -->.holdmygroza.

**Comment by wootguy** [comment]
The bug was that the texture scaling/shifting WIP feature breaks lighting.

This is the command i run to fix lighting when those features break it:
`hlrad -nobleedfix -estimate -waddir . -bounce 3 -extra mapname.bsp`
you might need to guess some values for lights.rad too
