### ISSUE TITLE
crash opening of_utbm

### ISSUE THREAD

**Issue by wootguy** [wootguy/bspguy#12]
[of_utbm.zip](https://github.com/wootguy/bspguy/files/5351875/of_utbm.zip)

also frac1b

**Comment by 2020karaulov2020** [comment]
> [of_utbm.zip](https://github.com/wootguy/bspguy/files/5351875/of_utbm.zip)
> 
> also frac1b

Nothing crashes when open file from this archive...

**Comment by wootguy** [comment]
Yep, not crashing now. This must have been fixed as part of something else.
