### ISSUE TITLE
GLFW Error: Invalid window size 0x0

### ISSUE THREAD

**Issue by wootguy** [wootguy/bspguy#17]
Add a sanity check to prevent this from happening.

As a workaround, delete your `%appdata%/bspguy/bspguy.cfg` file or edit the screen resolution values inside.

**Comment by 2020karaulov2020** [comment]
@wootguy to reproduce error need just minimize window and close it. After it you can't open bspguy)

**Comment by wootguy** [comment]
Can't reproduce that myself (Windows 10). Maybe an earlier version of windows does this?

**Comment by 2020karaulov2020** [comment]
> Can't reproduce that myself (Windows 10). Maybe an earlier version of windows does this?

Need minimize not maximized window. And close program from panel. (or task manager)

**Comment by wootguy** [comment]
Oh, that did it. I had the window maximized before.

**Comment by wootguy** [comment]
Fixed in #27.

Thanks for your help on these issues!
