### ISSUE TITLE
  add_subdirectory given source "glfw" which is not an existing directory.

### ISSUE THREAD

**Issue by 2020karaulov2020** [wootguy/bspguy#20]
add_subdirectory given source "glfw" which is not an existing directory.

![4eIgsCa 1](https://user-images.githubusercontent.com/62130676/108241616-15688280-715d-11eb-816a-812f1b00ed09.png)
![6PrCAfk 1](https://user-images.githubusercontent.com/62130676/108241637-1a2d3680-715d-11eb-8c5a-c928b06b4ee8.png)

**Comment by wootguy** [comment]
Extract `glfw` **next to** to the `src` folder, not **into** it. Same for the other libraries.

The path to glfw in this case should be `c:\Users\Admin\Downloads\bspguy-master\glfw`

**Comment by 2020karaulov2020** [comment]
> Extract `glfw` **next to** to the `src` folder, not **into** it. Same for the other libraries.
> 
> The path to glfw in this case should be `c:\Users\Admin\Downloads\bspguy-master\glfw`

@wootguy 
![f9bDVfN 1](https://user-images.githubusercontent.com/62130676/108305292-b8031e80-71ba-11eb-86b5-4d853e86f51b.png)

**Comment by 2020karaulov2020** [comment]
@wootguy  Okay, but after rename these directories I got next error : https://github.com/wootguy/bspguy/issues/21
