### ISSUE TITLE
missing file imgui\examples\imgui_impl_glfw.cpp

### ISSUE THREAD

**Issue by 2020karaulov2020** [wootguy/bspguy#21]
I tried to build bsgbuy but gor error: missing imgui\examples\imgui_impl_glfw.cpp file.

**Comment by wootguy** [comment]
project layout might have changed in a recent version of imgui. Try using this version instead:
https://github.com/ocornut/imgui/releases/tag/v1.78

**Comment by 2020karaulov2020** [comment]
@wootguy yes it works! Thanks! You can update links in readme ?((
