### ISSUE TITLE
Call function with ImGuiSliderFlags_Logarithmic flags

### ISSUE THREAD

**Issue by 2020karaulov2020** [wootguy/bspguy#22]
`Assertion failed: power == 1.0f && "Call function with ImGuiSliderFlags_Logarithmic flags instead of using the old 'float power' function!", file C:\Users\Admin\Downloads\bspguy-master\imgui\imgui_widgets.cpp, line 2436`

I got next error when open settings window and press "rendering"

**Comment by wootguy** [comment]
Try v1.77 or v1.76 of imgui. I'm not seeing that with v1.78 but it looks like that error is new to that version.

**Comment by 2020karaulov2020** [comment]
@wootguy  sorry I install 1.79 instead 1.78 ))) But in 'release' mode , no problems.

**Comment by 2020karaulov2020** [comment]
May be not, in 1.78 it added!


![ytvUV6E 1](https://user-images.githubusercontent.com/62130676/108309533-bb9aa380-71c2-11eb-9f2e-6358675af28c.png)

**Comment by wootguy** [comment]
oh I see the error now in Debug mode. I'll update the link in the readme.
