### ISSUE TITLE
Remove/Edit worldspawn ?

### ISSUE THREAD

**Issue by 2020karaulov2020** [wootguy/bspguy#31]
In map possible to use external BSP models. 

For example https://forums.alliedmods.net/showthread.php?t=318673

But it hard to create, because need add many lights around bsp model and compile it with bsp-nofill and without vis!

I can edit or remove worldspawn model from map via bspguy? _(or swap worldspawn with another and then remove)_

**Comment by wootguy** [comment]
If by worldspawn you mean the `*0` BSP model, then no that can't be edited in any way.

If by worldspawn model you mean any other BSP model, then yes you can edit and remove those. You can import a BSP model by creating an empty map with only your model, then merging that with the target map using the `merge` command.

**Comment by 2020karaulov2020** [comment]
> If by worldspawn you mean the `*0` BSP model, then no that can't be edited in any way.
> 
> If by worldspawn model you mean any other BSP model, then yes you can edit and remove those. You can import a BSP model by creating an empty map with only your model, then merging that with the target map using the `merge` command.

Yes ```*0``` model.  I can remove it from bsp ? (Or replace by empty ?)

**Comment by wootguy** [comment]
With a little new code it should be possible. Deleting all hulls from model 0 and running "clean" should do it.

**Comment by wootguy** [comment]
actually, this will delete all worldspawn model data:
`bspguy noclip de_test -model 0 -hull 0`
`bspguy noclip de_test -model 0`

**Comment by 2020karaulov2020** [comment]
> actually, this will delete all worldspawn model data:
> `bspguy noclip de_test -model 0 -hull 0`
> `bspguy noclip de_test -model 0`

It do model noclip, but model data still in bsp ?

**No command to replace models example**

bspguy swap de_test -model 1 -tomodel 0 ?

**Comment by wootguy** [comment]
The data will be completely deleted and all that will be left is the entity models.

Swapping models should be as easy as swapping headnodes. VIS info might break, not sure.

**Comment by 2020karaulov2020** [comment]
> The data will be completely deleted and all that will be left is the entity models.
> 

@wootguy after 'noclip' command model visibled in game or no?

**Comment by wootguy** [comment]
the model will be invisible if you noclip hull 0.
