### ISSUE TITLE
Decompiler

### ISSUE THREAD

**Issue by 2020karaulov2020** [wootguy/bspguy#38]
Possible to add feature export model to .map? (or whole bsp)

I tried to find decompiles with source code but not found any, then tried decompiled bspviewer and got some readable code:
[_003CModule_003E.zip](https://github.com/wootguy/bspguy/files/6056824/_003CModule_003E.zip)
Part of code https://pastebin.com/1Ai5hnGg 

But can't understand ))

**Comment by wootguy** [comment]
Exporting a convex model to .map should be easy, but most models aren't convex. Exporting a specific model to its own BSP would be doable, too.

> I tried to find decompiles with source code but not found any

mbspc is open source. I've never tried it though.
[mbspc.zip](https://github.com/wootguy/bspguy/files/6058494/mbspc.zip)
