### ISSUE TITLE
Corrupting files

### ISSUE THREAD

**Issue by GarompaEstomper** [wootguy/bspguy#4]
Hey very nice, this is what many people needed lately. Expect a lot of maps being fixed really fast with this.
Only real issue I find is that after saving a couple of times (the only thing I did was: change a spawnflag on an entity, and add 2 copies of a brush I moved somewhere else) the map BSP file ends up corrupted somehow, and plainly crashes the game and it cannot be loaded again through bspguy.
I will be testing more with it, I hope I am wrong about this one and touched something without knowing.
The obvious workaround is just to move each change made, manually, to another editor like bspedit or ented and use those only to save the changes, while keeping bspguy as the go-to tool for everything else.

**Comment by wootguy** [comment]
whoa, send the BSP and steps to reproduce and I'll get that fixed. Duplicating 2 brush entities didn't break anything for me (tried with/without `Duplicate BSP Model`).

**Comment by wootguy** [comment]
I managed to corrupt my map yesterday while messing with brushes, but I don't know how. I could see errors from the `Validate` command when it happening. Deleting the brush and running `Map` -> `Clean` fixed it.

**Comment by GarompaEstomper** [comment]
We managed to corrupt 2 maps today, but didn't move or copy any brushes. In my test, I received the edited maps, which worked fine ingame, but after I took them and made more modifications it started to crash. I also tested by opening it up in another editor (bspedit) and used that one to save, which made it crash as well. I even did just open the map and saved without doing anything, and that also corrupted the map.

**Comment by wootguy** [comment]
If you send me the corrupt file then I can try to see what's wrong with it. Without knowing which step caused the corruption it could be hard to fix though. It might just be a missing character or something in the entity data if you didn't touch any brushes.

**Comment by wootguy** [comment]
can't reproduce
