### ISSUE TITLE
BSPGuy Change Class Issue

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [wootguy/bspguy#48]
![Proof](https://user-images.githubusercontent.com/83011225/115704680-931a5b80-a363-11eb-80ba-efb9aecfcca4.png)

I have no idea what is going on, and it didn't even happen to me until now. I linked the paths to the .fgd files flawlessly, as well as the game directory, but nothing changed. This is specifically in regards to the change class tab, and I have to say, it does make me agree that BSPGuy still needs some polishing, though it might be best if it were to be released when its done.

When I clicked on the thing that makes a list of NPCs, functions, etc, it is almost to the brim of being empty apart from the "Change Class" and "Other" sentence, yet the "Other" tab has nothing in it either. What is going on?

**Comment by wootguy** [comment]
might be related to this:
https://github.com/wootguy/bspguy/issues/16#issuecomment-751418120

Check or post your log here if the FGD settings look fine. Idk what else it could be.
Widgets -> Log -> Right click -> Copy

**Comment by ToxicHolyGrenade** [comment]
I checked, but sadly nothing in the log is associated with the problem.

**Comment by wootguy** [comment]
If you send the FGDs and your FGD settings I can try to reproduce it on my end.

**Comment by ToxicHolyGrenade** [comment]
What do you mean?

And by the way, here is what my settings look like.

![Proof](https://user-images.githubusercontent.com/83011225/115825737-c4e1ff80-a401-11eb-9992-a27b84900a7c.png)

![Proof 2](https://user-images.githubusercontent.com/83011225/115825869-efcc5380-a401-11eb-8667-1a55254a71cb.png)

**Comment by wootguy** [comment]
I mean can you attach the FGD files here in a ZIP file? ZIPs can be attached when leaving a comment. I already have `half-life.fgd` but idk where `absolutezero.fgd` comes from.

Without the files I can only guess at a fix for this.

**Comment by ToxicHolyGrenade** [comment]
[Half-Life Absolute Zero FGD.zip](https://github.com/wootguy/bspguy/files/6372191/Half-Life.Absolute.Zero.FGD.zip)

**Comment by wootguy** [comment]
The file is empty (0 bytes). Remove it from the FGD list and you'll be able to change classes. Either that or move it to the bottom of the list.

**Comment by necros5505** [comment]
the .fgd file was originally in D:\Steam\steamapps\common\Sven Co-op\svencoop, I moved it to d: and applied the settings changes. Everything worked. Then i copied the .fgd to different places (steamapps, ...\common\, ...sven co-op, etc ), swapped between \ and /  everything worked fine
