### ISSUE TITLE
Copying ladders sends you flying

### ISSUE THREAD

**Issue by lymphoid** [wootguy/bspguy#49]
So I'd like to say I just found your program this morning, and I really appreciate the work that was put in. It has a lot of potential too. 

I am interested in working with moving brush-based entities around. I am encountering an issue with I move func_ladder's around. This is not a bug with BSPGuy, but its a result of the engine (because I got the same issue with BSPedit. Here's a video: https://www.youtube.com/watch?v=PfH8ZCB-WtY

Also I would like to know how to rotate brushes around. You can see if the video that the ladder (func_wall) is black. This is because I copied a func_wall from the opposite wall so you are seeing the un-lighted side. Can you not rotate brushes? I tried using "angle" "0 99 0", and similar commands using BSPEdit but that did not work.

**Comment by wootguy** [comment]
Weird that an origin change would cause that. I've only ever seen that when a ladder doesn't have a box-shaped collision brush. 

I think I moved the same ladder to roughly the same spot (top elevator in of2a2). I didn't fly away. Maybe something wasn't aligned right in your edit?

![image](https://user-images.githubusercontent.com/12087544/119250541-92890680-bb55-11eb-9761-8dde4d876640.png)

There's no rotate function yet. Best you can do is copy the texture from one face and paste it on the other side. Some entities ([func_wall](https://sites.google.com/site/svenmanor/entguide/func_wall)) have a flag that let you use the "angles" keys to orient them. Not sure if that's a Sven Co-op feature.

**Comment by lymphoid** [comment]
Thank you for the data. It's possible that scaling the func_ladder may have caused this, rather than moving it. I will do more testing this evening.

**Comment by wootguy** [comment]
possibly a bug in the v3 version then. There's a newer build that might work.
https://github.com/wootguy/bspguy/releases/tag/v4

**Comment by lymphoid** [comment]
I just tried again with both v3 and v4. I'm wondering if I am doing something wrong. Should I be doing a "copy and duplicate" or just a copy?

**Comment by wootguy** [comment]
Just a copy is enough, although duplicating doesn't hurt either. I tried both and didn't have problem strafing on the ladder. 🤔

**Comment by wootguy** [comment]
can't reproduce
