### ISSUE TITLE
Pi is wrong

### ISSUE THREAD

**Issue by stickyisle** [wootguy/bspguy#5]
util.h is using the wrong value for pi. Should be "#define PI 3.141593f" instead of "#define PI 3.141592f", since the next number is a 6.

Happy to help =)

**Comment by stickyisle** [comment]
H² says that pi from the C++ library is available via the constant "M_PI".

**Comment by wootguy** [comment]
send a pull request :>

**Comment by wootguy** [comment]
guess it's close enough
