### ISSUE TITLE
How to use extra texture?

### ISSUE THREAD

**Issue by q52888940** [wootguy/bspguy#51]
The texture is packaged in the map. I want to use other textures besides the map. Is this possible? Sorry for my bad English.
In addition, "GLFW Error: Invalid window size 0x0", the program cannot be opened, can I fix it with the EXE file, I cannot compile the source code.

**Comment by danylopez123** [comment]
I also wanted to see how i can replace a texture from a .wad file that the map it's using and not any texture that the map it's currently using.
I think that is yet to be implemented.

**Comment by wootguy** [comment]
> I want to use other textures besides the map. Is this possible?

You can do this with the `-textureexport` and `-textureimport` options in ripent (included with the Sven Co-op SDK). You can also force the map to use WAD textures using `bspguy unembed mapname.bsp`.

> GLFW Error: Invalid window size 0x0

see https://github.com/wootguy/bspguy/issues/17

> how i can replace a texture from a .wad file that the map it's using and not any texture that the map it's currently using.

Don't know what you're asking. Why not edit the texture in the WAD file? If the same texture is embedded in the BSP then you can unembed it with `bspguy unembed mapname.bsp`. That way the map is forced to use your edited WAD (as long as it's referenced in the `wad` keyvalue of the `worldspawn` entity).

There are also some WIP features by karaulov that can import/export WADs similar to how ripent does it, but you need to compile the latest source for that.
