### ISSUE TITLE
Installing on Linux Issues

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [wootguy/bspguy#59]
While the earlier steps are very clear and understandable, the step that requires opening a 'shell' and entering the aforementioned commands, is something that tends to be confusing. Would you possibly be overhauling the Linux build of BSPGuy at a certain future point, and make it a true application for it? What is the specified shell that was meant to be used?

**Comment by ToxicHolyGrenade** [comment]
Even if I had finally linked it to the CMakeLists file, I get this instead.

"andrew@andrew-Alienware-Aurora-R9:~/build$ cmake .. -DCMAKE_BUILD_TYPE=RELEASE
-- Configuring done
CMake Error at CMakeLists.txt:81 (add_executable):
  Cannot find source file:

    imgui/imgui.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:81 (add_executable):
  No SOURCES given to target: bspguy


CMake Generate step failed.  Build files cannot be regenerated correctly."

Is there something faulty with the CMakeLists file?

**Comment by ToxicHolyGrenade** [comment]
Successfully, I finally managed to get somewhere, but now I've ran into another issue, and its this.

"Linking CXX executable bspguy
/usr/bin/ld: cannot find -lXxf86vm
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bspguy.dir/build.make:658: bspguy] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/bspguy.dir/all] Error 2
make: *** [Makefile:103: all] Error 2"

Is there any way to fix this Wootguy?

**Comment by ToxicHolyGrenade** [comment]
And also, how do I get rid of this error as well?

"In file included from /home/andrew/bspguy/src/bsp/bsptypes.cpp:1:
/home/andrew/bspguy/src/bsp/bsptypes.h:73:9: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]"

**Comment by wootguy** [comment]
> /usr/bin/ld: cannot find -lXxf86vm

Googled that library name and it looks like you can maybe get it with this command:
`sudo apt install libgl1-mesa-dev xorg-dev`

> warning: ISO C++ forbids converting a string constant to ‘char*’ 

That's just a warning. The compile will succeed despite that.

**Comment by ToxicHolyGrenade** [comment]
Finally got it to work. Thanks very much wootguy. 😉👍

**Comment by ToxicHolyGrenade** [comment]
I guess its all because, the commands are incapable of building the source effectively. It'll be best if the instructions of building the Linux version source, is updated. The commands that Chris Titus Tech shown, words on a wide scale of Linux operating systems. I suggest checking it out, its great stuff. :)

https://www.youtube.com/watch?v=atSZAbyrjxU

**Comment by wootguy** [comment]
Seems like the trouble comes from dependencies. The steps he followed were basically the same, but he installed `build-essential`. I'll add `build-essential libgl1-mesa-dev xorg-dev` to the first step and that hopefully will cover most distros.
