### ISSUE TITLE
Saving BSPGuy Options

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [wootguy/bspguy#61]
On Linux, I did manage to get BSPGuy running via CrossOver, but the main drawback, is that BSPGuy does not save the options that I had devised, pretty much the FGDs and options in particular. Any ideas on how to fix that?

**Comment by wootguy** [comment]
What does the error message say?

**Comment by ToxicHolyGrenade** [comment]
Failed to open user config: C:\users\crossover\AppData\Roaming\bspguy\bspguy.cfg
Missing FGD: /svencoop/sven-coop.fgd
Missing WAD: halflife.wad
Missing WAD: decals.wad
Missing WAD: liquids.wad
Missing WAD: xeno.wad
Missing WAD: opfor.wad

**Comment by wootguy** [comment]
I'm guessing that folder path doesn't exist and the program doesn't have permission to create it. You could try creating the folders and file manually, then try to save options again. [Building for Linux](https://github.com/wootguy/bspguy/issues/59) might also be less error prone.

**Comment by ToxicHolyGrenade** [comment]
Actually, I did already check for the folder, as well as the configuration file, but regardless, it still cannot load the cfg file at all. This is why I am hoping, as opposed to calling for, an actual Linux version of BSPGuy, as opposed to building it from scratch. Not saying you need to build it now, but at a certain future point hopefully.

**Comment by ToxicHolyGrenade** [comment]
And by folder, I mean the directory. Both it, the folders, as well as the configuration file exists, but BSPGuy still cannot load it from CrossOver.

**Comment by ToxicHolyGrenade** [comment]
So yes, just something to think about.

**Comment by ToxicHolyGrenade** [comment]
Actually, I did already check for the folder, as well as the configuration file, but regardless, it still cannot load the cfg file at all. This is why I am hoping, as opposed to calling for, an actual Linux version of BSPGuy, as opposed to building it from scratch. Not saying you need to build it now, but at a certain future point hopefully.

And by folder, I mean the directory. Both it, the folders, as well as the configuration file exists, but BSPGuy still cannot load it from CrossOver.

**Comment by wootguy** [comment]
Not going to support crossover or wine. A Linux build should be used instead.
