### ISSUE TITLE
Interrelated surfaces

### ISSUE THREAD

**Issue by moptex** [wootguy/bspguy#63]
Let's say I copied any func_wall. I need to change the texture on the new func_wall. When I open the "Face Editor" function for the new func_wall, then both surfaces, the old and the new func_wall, are selected, although I only need the new one. Please make sure that when copying new objects, the surfaces of the old and new objects are not interconnected.

**Comment by wootguy** [comment]
Click "Duplicate BSP model" in the right-click menu for the new func_wall and you'll be able to edit the models separately. This isn't done automatically because every new model takes up precious space in the BSP.
