### ISSUE TITLE
"Classname Filter"

### ISSUE THREAD

**Issue by moptex** [wootguy/bspguy#66]
In the "Entity Report" section, the "Classname Filter" function does not work. Please fix this. Please.

**Comment by wootguy** [comment]
Is [this ](https://github.com/wootguy/bspguy/issues/18) what you're seeing? Or is something else wrong with it?

**Comment by moptex** [comment]
I am running "bspguy v3 (build 252)". This function does not work for me at all.

**Comment by wootguy** [comment]
It might have something to do with the FGDs that are loaded. Like how the class-change button breaks when an FGD fails to load or is empty.

I'm curious where "(build 252)" comes from. I've never used build numbers. [v4](https://github.com/wootguy/bspguy/releases/tag/v4) is worth a try.

**Comment by moptex** [comment]
Good. I will try the new version. Haven't you worked on Issues # 55 yet? I really need a solution to this problem.

**Comment by wootguy** [comment]
#55 is a huge amount of work and  I probably won't ever do it. I think it involves recompiling the map using faces instead of brushes, which is something I've tried and failed to do already. Someone who knows more about the map compilers can probably figure it out.

**Comment by wootguy** [comment]
> Good. I will try the new version. Haven't you worked on Issues # 55 yet? I really need a solution to this problem.

Does it work in v4?

**Comment by wootguy** [comment]
guessing it works in v4
