### ISSUE TITLE
Crash deleting entity

### ISSUE THREAD

**Issue by wootguy** [wootguy/bspguy#68]
Happens on Windows 7, and sometimes on Windows 10.

Delete the entity named "chapter_tittle" in this map:
[rp_c00_m1.zip](https://github.com/wootguy/bspguy/files/7670115/rp_c00_m1.zip)

**Comment by UnrealKaraulov** [comment]
File marked as 'read only' in properties.

But even with this, I can't get crash in v4.

**Comment by UnrealKaraulov** [comment]
> Happens on Windows 7, and sometimes on Windows 10.
> 
> Delete the entity named "chapter_tittle" in this map: [rp_c00_m1.zip](https://github.com/wootguy/bspguy/files/7670115/rp_c00_m1.zip)

@wootguy File marked as 'read only' in properties.

But even with this, I can't get crash in v4.

**Comment by wootguy** [comment]
not happening anymore in master, built with VS 2019 on Windows 7.
