### ISSUE TITLE
black background

### ISSUE THREAD

**Issue by dylxnztm** [wootguy/bspguy#69]
I had restarted the computer due to a problem, when I open bspguy, any map that I try to edit does not load and it shows a whole black background. Apparently, it had been "misconfigured", I tried to fix it by configuring the game directory and the fgd correctly, in addition to trying each option in the settings part, but everything remains the same...
Maybe the problem is quite basic, but since I have just started to edit maps, there are many things that I do not know :(
ps: I drag the map to the executable as indicated, and when I go to the entity report the "no map selected" appears ..

**Comment by wootguy** [comment]
Try deleting the `%appdata%/bspguy/` folder to reset everything to default. Maybe those files were corrupted when restarting.

**Comment by wootguy** [comment]
guessing that fixed it
