### ISSUE TITLE
What does clean and optimize do?

### ISSUE THREAD

**Issue by seedee** [wootguy/bspguy#7]
It's not made clear

**Comment by wootguy** [comment]
clean removes unused data that accumulates after editing BSP models. Maps might also have lots of unused data to begin with (of1a1.bsp has 13k unused planes for some reason). Deleting all references to a BSP model will also cause clean to delete that model.

optimize is explained [here](https://github.com/wootguy/bspguy/wiki/Merging-workflow#optimize). Don't use it in v3 though. There's a bug that deletes a required hull from func_ladder, with no way to recover it. The latest commit should be safe(r).
