### ISSUE TITLE
imgui: error compiling on debian

### ISSUE THREAD

**Issue by fred0r** [wootguy/bspguy#70]
```
Linking CXX executable bspguy
/usr/bin/ld: CMakeFiles/bspguy.dir/imgui/backends/imgui_impl_opengl3.cpp.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bspguy.dir/build.make:689: bspguy] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/bspguy.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by wootguy** [comment]
Haven't seen that before. The latest commit builds on Lubuntu. All I can think to try is use different versions of imgui or [google the error messages](https://askubuntu.com/questions/1098073/g-fails-with-an-undefined-reference-to-symbol-dlcloseglibc-2-2-5-even-with).

**Comment by fred0r** [comment]
i already did before writing this issue and it seems that the cmake-buildparameters need to be edited/tweaked, but i dont know anything about this :/
there are also a lot of issues in the imgui-issues about that topic.
i tried with latest v1.81 imgui and also with the latest git.
