### ISSUE TITLE
multi_manager can't have same targets

### ISSUE THREAD

**Issue by Cads182** [wootguy/bspguy#74]
Seems that you can't have two same targets ( I wanted to trigger twice an entity in different times).

**Comment by wootguy** [comment]
The same is true in Hammer, except Hammer automatically adds the hashtag suffixes to triggers with the same name. Use these keyvalue names to trigger `doot` multiple times:
`doot`
`doot#1`
`doot#2`

**Comment by Cads182** [comment]
Great, thanks!
