### ISSUE TITLE
Crash on optimizing of some maps

### ISSUE THREAD

**Issue by Qwertyus3D** [wootguy/bspguy#78]
As said above, Optimize doesn't work for some maps because of instant CTD.
[crash.zip](https://github.com/wootguy/bspguy/files/8104820/crash.zip)

**Comment by Qwertyus3D** [comment]
Here are another 2 maps, the difference is they have clipnodes limit exceeded (though they were compiled successfully).

P. S. "Clean" function also causes CTD for those maps.
[limit.zip](https://github.com/wootguy/bspguy/files/8104853/limit.zip)

**Comment by UnrealKaraulov** [comment]
crash at vis decompress function

**Comment by UnrealKaraulov** [comment]
out of bounds

**Comment by wootguy** [comment]
> they have clipnodes limit exceeded (though they were compiled successfully).

I wonder which compiler allowed that to happen 🤔
