### ISSUE TITLE
Can't get out of a right click unless selecting a option, clicking on the bottom "shared data" message or top menu

### ISSUE THREAD

**Issue by R4to0** [wootguy/bspguy#8]
![1599070595](https://user-images.githubusercontent.com/3608184/92021743-98715a00-ed30-11ea-8a2f-c302959573a9.gif)

**Comment by wootguy** [comment]
This was a regression in ImGui 1.77. It's fixed in [1.78](https://github.com/ocornut/imgui/releases/tag/v1.78).

**Comment by R4to0** [comment]
Turns out it was a bug with imgui v1.77, updating it to latest version (1.78) fixes this issue.
