### ISSUE TITLE
Optimize eliminates trigger_autosave

### ISSUE THREAD

**Issue by Qwertyus3D** [wootguy/bspguy#81]
I know that the program was intended to work for Sven Co-op needs, but someone may need to use it for singleplayer, so please make the deleting all hulls of trigger_autosave on Optimize optional. Also, I'm not sure if trigger_autosave is the only SP entity which is being screwed by Optimize, maybe there are more of them.

**Comment by wootguy** [comment]
It's probably a lot more than just trigger_autosave. Each game/mod would need a sort of config file that defines which hulls are ok to delete from its custom entities.
