### ISSUE TITLE
"Clean" and hull deleting do not reduce clipnodes limit

### ISSUE THREAD

**Issue by Qwertyus3D** [wootguy/bspguy#82]
I'm not sure how this is intended to work, I just assume that if you clean or delete something, than you should get a clipnode count reduced. But, in fact, only "Optimize" function affects clipnode count. Though, if I understand it right, it's intended to clean the map and delete unneded hulls too. So it looks like a bug or a missing function of updating map properties after some manual operations.

**Comment by UnrealKaraulov** [comment]
You can bypass any limit with export part of map to BSP model, and then import back as func_breakable

**Comment by Qwertyus3D** [comment]
With map sources I probably do not need BSPGuy ;)

I also found another related issue. After editing a map with BSPGuy and reopening it again I see there errorneous bsp model with "???" name (it shows up in Clipnodes count list). It's pretending to use a pretty much of clipnodes, but in fact its' clipnodes do not increase the overall clipnodes count. This model can be removed with "Clean" option though.

**Comment by wootguy** [comment]
The clipnode count will be reduced only if you delete all entities that reference a model that's using up clipnodes. You need to do a `clean` after that to delete the model and see the clipnodes amount change.

`???` means that the model is not referenced in any entity, so the next `clean` will delete it and free up some space.
