### ISSUE TITLE
Relative paths in path settings

### ISSUE THREAD

**Issue by Adambean** [wootguy/bspguy#9]
Would it be possible to support relative paths in path settings? (Currently just game directory and FGDs.)

Reason: I have a portable GoldSrc development folder at "some portable location" with some sub folders:

- compile
- decompile
- fgd
- maps
- resources
- sources
- textures
- tools
- ... and more

I put "bspguy.exe" in "decompile" because that's what it's for, so in my case it would be neat if the FGD paths could be relative, such as `../fgd/Sven Co-op 5.23.fgd` or `..\fgd\Sven Co-op 5.23.fgd` instead of an absolute (and sometimes changing) path.

This may require use of an `$AppDir` placeholder to insert the current path name of the directory the application resides in.

**Comment by wootguy** [comment]
Sure, I didn't think of using it this way.

**Comment by 2020karaulov2020** [comment]
@wootguy is this issue still there?

**Comment by wootguy** [comment]
#26 fixes this.

"Asset paths" (for finding WADs) and "FGDs" can be relative to the working directory or "Game Directory". Relative paths currently need to start with a slash.

**Comment by 2020karaulov2020** [comment]
@wootguy but global settings path anyway non portable. May be for window user need save settings in same folder(where bspguy.exe located)?

**Comment by wootguy** [comment]
That's a different issue, but I can see a local settings file being useful (at least for game-related settings).

**Comment by Adambean** [comment]
Thank you kindly for that update @2020karaulov2020
