### ISSUE TITLE
BSPGuy Master - Merging & Exporting Textures

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [wootguy/bspguy#91]
Since I have successfully downloaded BSPGuy Master, how do you use the merging and exporting of textures?

**Comment by wootguy** [comment]
I forgot how it works, and the discussion about it was deleted. There should be an import/export button in one of the drop-down menus. It might be that it replaces textures that are already in the BSP, not embedding new ones. @UnrealKaraulov do you remember?

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade , @wootguy 

I don't remember how it works in master, but in my fork, it works:

**File->Embedded textures (.wad)**
to export all textures to external .wad file, and removing it from map.
**File->"Merge with .wad**
to import all textures from external .wad file to map

**Comment by guigolinhos** [comment]
Whats BSPGuy Master?

**Comment by UnrealKaraulov** [comment]
@guigolinhos builded from this source code, or you can test my fork https://github.com/UnrealKaraulov/newbspguy

@wootguy this issue can be closed if question answered ?

**Comment by wootguy** [comment]
I just checked the code and works a little differently from your fork:

Importing a wad = embeds all textures from that WAD into the BSP. No existing embedded textures are overwritten, so you can't replace a texture this way. Use ripent to edit textures instead.

Exporting a wad = All embedded textures in the BSP are written to a WAD file. Nothing is deleted from the BSP, so you can't remove embedded textures this way. You can use the "unembed" command if you want that.
