### ISSUE TITLE
Any More Future Versions?

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [wootguy/bspguy#99]
Since it has been over a year since the last updates, would there be any more future versions of BSPGuy, with new additions and many fixes?

**Comment by wootguy** [comment]
Maybe, but it's working well enough for what I need.

**Comment by wootguy** [comment]
I agree those are good things to add/fix. Maybe one day they'll get done. Maybe not by me. That's the upside of this project being open-source. I can lose interest and anyone else can pick up where I left off.
